### ISSUE TITLE
dsfdr error

### ISSUE THREAD

**Issue by rkmandal1** [serenejiang/q2_dsfdr#4]
I am getting the following error while using dsfdr plugin in qiime2-2017.12. Command is as follows-

qiime dsfdr permutation-fdr --i-table table.qza --m-metadata-file metadata.tsv --m-metadata-category MStatus --output-dir test-dsFDR

Plugin error from dsfdr:

  'module' object is not callable

Debug info has been saved to /var/folders/64/58fk04bx2335w895j8x608080000gn/T/qiime2-q2cli-err-tx3k5t3k.log

and log file looks like this-

Traceback (most recent call last):
  File "/Users/Schmidtlab/anaconda3/envs/qiime2-2017.12/lib/python3.5/site-packages/q2cli/commands.py", line 224, in __call__
    results = action(**arguments)
  File "<decorator-gen-286>", line 2, in permutation_fdr
  File "/Users/Schmidtlab/anaconda3/envs/qiime2-2017.12/lib/python3.5/site-packages/qiime2/sdk/action.py", line 228, in bound_callable
    output_types, provenance)
  File "/Users/Schmidtlab/anaconda3/envs/qiime2-2017.12/lib/python3.5/site-packages/qiime2/sdk/action.py", line 363, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/Users/Schmidtlab/anaconda3/envs/qiime2-2017.12/lib/python3.5/site-packages/q2_dsfdr/plugin_setup.py", line 40, in permutation_fdr
    alpha, permutations)
TypeError: 'module' object is not callable

Please let me know.

Thanks,
Rabindra

**Comment by serenejiang** [comment]
@rkmandal1 We have fixed the errors in the plug-in; it should be ready to be used now. Please check the [demo notebook](https://github.com/serenejiang/q2_dsfdr/blob/master/demo/small%20example%20of%20using%20Q2-DSFDR.ipynb). Thanks!
